import classNames from "classnames";
import "../css/globals.css";

export const metadata = {
  title: "Markdown Editor",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={classNames(
          "bg-gradient-to-b",
          "from-[#121212]",
          "via-[#1E1E1E]",
          "to-[#121212]"
        )}
      >
        {children}
      </body>
    </html>
  );
}
